first_action:
    pattern: /simpleResponse
    defaults: {_controller: AcmeDemoBundle:Hometask:simpleResponse}
second_action:
    pattern: /simpleTemplate
    defaults: {_controller: AcmeDemoBundle:Hometask:simpleTemplate}
third_action:
    pattern: /extendedTemplate
    defaults: {_controller: AcmeDemoBundle:Hometask:extendedTemplate}
